version: "3.7"
name: assistance-cron
services:

 assistance-cron:
    build: 
      context: .
      dockerfile: Dockerfile
    # depends_on:
    #   - indexer_mongo_db
    command: python3 -m http.server 1026
    environment:
      LOG_LEVEL: DEBUG
      LOG_FORMAT: "%(asctime)s :: %(levelname)s :: %(funcName)s :: %(message)s"
      IP: "172.25.0.70"
      credentials_file: /src/credentials/credentials.json
      ommit_ping: "True"
      verbose: "True"
      force_udp: "False"
    volumes:
      - ./:/src      
    networks:
      - frontend

networks:
  frontend:
    external: false